config/routes.rb
Bookmarker::Application.routes.draw do
  root :to => "folders#index"
  resources :folders do
    resources :links
  end

end

app/models/folder.rb
class Folder < ActiveRecord::Base
  has_many :links, :dependent => :delete_all
  
  attr_accessible :name, :parent, :parentname 
  serialize :parent
  validates :name, :presence => true, :uniqueness => true
  
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :folder
  
  attr_accessible :notes, :title, :url, :timestamp
  
  validates :title, :url, :presence => true
  validates :url, :uniqueness => true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  
  before_filter :find_folder, :only => [:edit, :update, :destroy, :show]
  before_filter :get_folders
  before_filter :get_all_sorted_links, :only => [:index]
  
  def index
  end
  
  def new
    if params[:parentname].nil?
      @folder = Folder.new(:parentname => "All")
    else
      @folder = Folder.new(:parentname => params[:parentname])
    end
  end

  def create
    @folder = Folder.new(params[:folder])
    title = @folder.name
    if @folder.save
      flash[:notice] = "Your folder #{title} has been created."
      redirect_to folders_path
    else
      flash[:alert] = "Your folder has not been created."
    end
  end

  def edit
  end

  def update
    if @folder.update_attributes(params[:folder])
      flash[:notice] = "Your folder has been updated."
      redirect_to folders_path
    else
      flash[:alert] = "Your folder has not been updated."
      render :action => :edit
    end
    
  end

  def destroy
    name = @folder.name
    @folder.destroy
    @folders = Folder.all.sort! { |a,b| a.name.downcase <=> b.name.downcase }
    flash[:notice] = "Your folder #{name} has been deleted."
    redirect_to folders_path
  end
  

  def show
    @links = @folder.links.sort! { |a,b| b.timestamp <=> a.timestamp }
  end
  
  private
 
  def find_folder
    @folder = Folder.find(params[:id])
  end
  
  def get_folders
    if @root.nil?
      @root = Folder.new(:name => "All", :parentname => "All")
      @root.save      
    end
    @folders = Folder.where("name <> 'All'")
    @folders.sort! { |a,b| a.name.downcase <=> b.name.downcase }
  end
  
  def get_all_sorted_links
    @links = Link.all
    # revert to ABC sort--  @links.sort! { |a,b| a.title.downcase <=> b.title.downcase }
    @links.sort! { |a,b| b.timestamp <=> a.timestamp }
  end
  
  def sort_folders
    @all = []
    
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :find_folder
  before_filter :find_link, :only => [:edit, :show, :update, :destroy]
  
  def index
    redirect_to folder_path(@folder)
  end
  
  def new
    @link = @folder.links.build
  end

  def create
    @link = @folder.links.build(params[:link])
    @link.timestamp = Time.now.to_i
    unless @link.url.include? "http://"
      url = 'http://' + @link.url
      @link.url = url
    end
    if @link.save
      title = @link.title
      flash[:notice] = "Your link #{title} has been created."
      redirect_to folder_path(@folder)
    else
      flash[:alert] = "Your link has not been created."
      render :action => :new
    end
  end

  def edit
  end

  def update
    @link.timestamp = Time.now.to_i
    if @link.update_attributes(params[:link])
      flash[:notice] = "Your link has been updated."
      redirect_to folders_path
    else
      flash[:alert] = "Your link has not been updated."
      render :action => :edit
    end 
  end

  def destroy
    title = @link.title
    @link.destroy
    flash[:notice] = "Your link #{title} has been deleted."
    redirect_to root_path
  end  
  
  private
  
  def find_folder
   @folder = Folder.find(params[:folder_id]) 
  end
    
  def find_link
    @link = @folder.links.find(params[:id])
  end
  
  def find_folder_links
    @links = @folder.links
    @links.sort! { |a,b| a.title.downcase <=> b.title.downcase }
  end
end

app/controllers/models_controller.rb
class ModelsController < ApplicationController
  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/folder_helper.rb
module FolderHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/views/folders/_form.html.erb
<%= form_for(@folder) do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
    <%= f.hidden_field :parentname %>
	</p>
   <%= f.submit %>
<% end %>

app/views/folders/_linklist.html.erb
<ul>
<% unless @links.nil? %>	
	<% @links.each do |link| %>
		<% folder = Folder.find(link.folder_id) %>
			<h3><div class='links' id='<%= link.title %>'>
				<a href="<%= link.url.to_s %>"><%= link.title %></a></h3>
				<ul>

					<li>
						<div class ='links-url'><%= link.url %></div>				
					</li>								

					<% unless link.notes.empty? %>
					<li>
						<div class='links-notes' id='<%= link.title %>'>
							<%= link.notes %>
						</div>
					</li>
					<% end %>
  				Filed under <%= folder.name %> | <%= link_to "Edit", [:edit, folder, link] %> | <%= link_to "Delete", [folder, link], :method => :delete, :confirm => "Are you sure you want to delete this link?" %>
					<br />
				</ul>
	<% end %>
<% end %>
</ul>

app/views/folders/create.html.erb
<h1>Folder#create</h1>
<p>Find me in app/views/folder/create.html.erb</p>

app/views/folders/destroy.html.erb
<h1>Folder#destroy</h1>
<p>Find me in app/views/folder/destroy.html.erb</p>

app/views/folders/edit.html.erb
<h2>Edit Folder</h2>

<%= render 'form' %>

app/views/folders/index.html.erb
<!-- Display all links -->

<%= render 'linklist' %>

app/views/folders/new.html.erb
<h1>New Folder</h1>

<%= render 'form' %>

app/views/folders/new_sub.html.erb
<h1>New Subfolder</h1>

<%= render 'form' %>

app/views/folders/show.html.erb
<h2><%= @folder.name %></h2>

<%= "Filed under... " + @folder.parentname.to_s %><br />

<%= link_to "Add a link", new_folder_link_path(@folder) %>
<%= link_to "Create Subfolder", new_folder_path(:parentname => @folder.name) %>
<%= link_to "Edit Folder", edit_folder_path %>
<%= link_to "Delete Folder", @folder, :method => :delete, :confirm => "Are you sure you want to delete this folder?"%>

<%= render 'linklist' %>

app/views/folders/update.html.erb
<h1>Folder#update</h1>
<p>Find me in app/views/folder/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmarker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1><%= link_to "Bookmarker", root_path %></h1>
<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>


<h2><%= link_to "Folders", root_path %></h2>
<%= link_to "New Folder", new_folder_path %><br /><br />

<%= link_to "All", root_path %>
<% unless @folders.nil? %>
	<% @folders.each do |folder| %>
		<div class='folders' id='<%= folder.name %>'>
			<b><%= link_to folder.name, folder %></b><br />
		</div>
	<% end %>
<% end %>

<br />
<br />

<%= yield %>


</body>
</html>

app/views/links/_form.html.erb
<%= form_for [@folder, @link] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
	</p>
  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
	</p>
  <p>
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
	</p>
   <%= f.submit %>
<% end %>

app/views/links/create.html.erb
<h1>Links#create</h1>
<p>Find me in app/views/links/create.html.erb</p>

app/views/links/destroy.html.erb
<h1>Links#destroy</h1>
<p>Find me in app/views/links/destroy.html.erb</p>

app/views/links/edit.html.erb
<h2>Edit Link</h2>

<%= render 'form' %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

app/views/links/show.html.erb
<h1>Links#show</h1>
<p>Find me in app/views/links/show.html.erb</p>

app/views/links/update.html.erb
<h1>Links#update</h1>
<p>Find me in app/views/links/update.html.erb</p>

app/views/models/create.html.erb
<h1>Models#create</h1>
<p>Find me in app/views/models/create.html.erb</p>

app/views/models/destroy.html.erb
<h1>Models#destroy</h1>
<p>Find me in app/views/models/destroy.html.erb</p>

app/views/models/edit.html.erb
<h1>Models#edit</h1>
<p>Find me in app/views/models/edit.html.erb</p>

app/views/models/new.html.erb
<h1>Models#new</h1>
<p>Find me in app/views/models/new.html.erb</p>

app/views/models/show.html.erb
<h1>Models#show</h1>
<p>Find me in app/views/models/show.html.erb</p>

app/views/models/update.html.erb
<h1>Models#update</h1>
<p>Find me in app/views/models/update.html.erb</p>